AulaEstancia:
    type: entity
    table: aulas_estancias
    id:
        id:
            type: integer
            generator:
            strategy: AUTO
    fields:
        nombre:
            type: string
            length: 255
