App\Entity\Profesores:
    type: entity
    table: profesores
    indexes:
        fk_profesores_departamentos1_idx:
            columns:
                - id_departamento
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        nombre:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        apellidos:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        usuario:
            type: string
            nullable: false
            length: 200
            options:
                fixed: false
        password:
            type: string
            nullable: false
            length: 200
            options:
                fixed: false
        correo:
            type: string
            nullable: false
            length: 200
            options:
                fixed: false
    manyToOne:
        idDepartamento:
            targetEntity: Departamentos
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_departamento:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
