App\Entity\TiposIncidencias:
    type: entity
    table: tipos_incidencias
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        tipoIncidencia:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: tipo_incidencia
        descripcion:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
    lifecycleCallbacks: {  }
